# Generated by Django 5.0.3 on 2024-04-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEquipmentWorkingInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=100, verbose_name='省份')),
                ('device_name', models.CharField(default='未知设备', max_length=20, verbose_name='设备名称')),
                ('device_type', models.CharField(default='未知类型', max_length=20, verbose_name='设备类型')),
                ('type_in', models.CharField(choices=[('综合性发电', '综合性发电'), ('火电厂', '火电厂'), ('水电厂', '水电厂'), ('光电场', '光电场'), ('风电场', '风电场')], default='综合性发电', max_length=100, verbose_name='隶属电场类型')),
                ('device_state', models.CharField(choices=[('正常', '正常'), ('异常', '异常')], default='正常', max_length=10, verbose_name='设备状态')),
                ('device_information', models.CharField(default='未知', max_length=50, verbose_name='设备实时信息')),
                ('when', models.DateField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '基地设备运行相关信息',
            },
        ),
        migrations.CreateModel(
            name='ElectricFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=100, verbose_name='省份')),
                ('city', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='合肥', max_length=10, verbose_name='市级')),
                ('station_type', models.CharField(choices=[('综合性发电', '综合性发电'), ('火电厂', '火电厂'), ('水电厂', '水电厂'), ('光电场', '光电场'), ('风电场', '风电场')], default='综合性发电', max_length=100, verbose_name='隶属电场类型')),
                ('station_name', models.CharField(max_length=100, null=True, verbose_name='电场名称')),
                ('state', models.BooleanField(default=True, verbose_name='运行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '电场信息',
            },
        ),
        migrations.CreateModel(
            name='ElectricFieldFaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malfunction_reason', models.CharField(max_length=100, verbose_name='故障原因')),
                ('send_times', models.IntegerField(default=0, verbose_name='通知维修次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('electric_field', models.ForeignKey(limit_choices_to={'state': False}, on_delete=django.db.models.deletion.CASCADE, to='PowerGenerationBase.electricfieldmodel', unique=True, verbose_name='电场信息')),
            ],
            options={
                'verbose_name_plural': '电场故障',
            },
        ),
        migrations.CreateModel(
            name='BaseDistributionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=100, verbose_name='范围')),
                ('thing', models.CharField(default='一号电厂', max_length=10, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('electric_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PowerGenerationBase.electricfieldmodel', unique=True, verbose_name='电场信息')),
            ],
            options={
                'verbose_name_plural': '基地分布',
                'unique_together': {('electric_field', 'thing')},
            },
        ),
    ]
