# Generated by Django 5.0.3 on 2024-03-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, null=True, verbose_name='省级')),
                ('station_type', models.CharField(choices=[('综合性发电', '综合性发电'), ('火力发电', '火力发电'), ('水力发电', '水力发电'), ('风力发电', '风力发电'), ('太阳能发电', '太阳能发电')], max_length=100, verbose_name='电场类型')),
                ('station_name', models.CharField(max_length=100, null=True, verbose_name='电场名称')),
                ('state', models.BooleanField(default=True, verbose_name='运行状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '电场信息',
            },
        ),
        migrations.CreateModel(
            name='ElectricFieldFaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malfunction_reason', models.CharField(max_length=100, verbose_name='故障原因')),
                ('send_times', models.IntegerField(default=0, verbose_name='通知维修次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('electric_field', models.ForeignKey(limit_choices_to={'state': False}, on_delete=django.db.models.deletion.CASCADE, to='PowerGenerationBase.electricfieldmodel', unique=True, verbose_name='电场信息')),
            ],
            options={
                'verbose_name_plural': '电场故障',
            },
        ),
    ]
