# Generated by Django 5.0.3 on 2024-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0002_marketinvestmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinvestmentmodel',
            name='electricity_trading',
        ),
        migrations.RemoveField(
            model_name='marketinvestmentmodel',
            name='energy_investment',
        ),
        migrations.RemoveField(
            model_name='marketinvestmentmodel',
            name='new_energy_storage_projects',
        ),
        migrations.RemoveField(
            model_name='marketinvestmentmodel',
            name='new_energy_storage_projects_power',
        ),
        migrations.AddField(
            model_name='marketinvestmentmodel',
            name='coal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='百亿千瓦时', max_digits=10, verbose_name='原煤产量'),
        ),
        migrations.AddField(
            model_name='marketinvestmentmodel',
            name='natural_gas',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='百亿千瓦时', max_digits=10, verbose_name='天然气产量'),
        ),
    ]
