# Generated by Django 5.0.3 on 2024-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0003_remove_marketinvestmentmodel_electricity_trading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinvestmentmodel',
            name='coal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万吨', max_digits=10, verbose_name='原煤产量'),
        ),
        migrations.AlterField(
            model_name='marketinvestmentmodel',
            name='natural_gas',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='亿立方米', max_digits=10, verbose_name='天然气累计消费量'),
        ),
    ]
