# Generated by Django 5.0.3 on 2024-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limited', '0004_alter_marketinvestmentmodel_coal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinvestmentmodel',
            name='coal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='千万吨', max_digits=10, verbose_name='原煤产量'),
        ),
    ]
