# Generated by Django 5.0.3 on 2024-04-23 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityStructureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=100, null=True, verbose_name='省级')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('wind', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='风能')),
                ('water', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='水利')),
                ('light', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='光伏')),
                ('biomass', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='质能')),
                ('sea', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='海洋')),
                ('hydrogen', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='氢能')),
                ('shale_oil', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='页岩油')),
                ('coal', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='煤炭')),
                ('petroleum', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='石油')),
                ('natural_gas', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='天然气')),
                ('geothermal', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='地热')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源产能及结构',
            },
        ),
        migrations.CreateModel(
            name='ConsumptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=100, null=True, verbose_name='省级')),
                ('total_energy_consumption', models.DecimalField(decimal_places=2, default=1.0, help_text='万吨标准煤', max_digits=10, verbose_name='能源消费总量')),
                ('coal', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='煤炭占比')),
                ('petroleum', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='石油占比')),
                ('natural_gas', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='天然气占比')),
                ('power_and_other', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='一次电力及其他能源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源消耗水平',
            },
        ),
        migrations.CreateModel(
            name='HeatMapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=100, null=True, verbose_name='省级')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='市级')),
                ('value', models.FloatField(null=True, verbose_name='数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源发展情况(权重)',
            },
        ),
    ]
