# Generated by Django 5.0.3 on 2024-03-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_heatmapmodel_province_alter_heatmapmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatmapmodel',
            options={'verbose_name_plural': '能源发展情况(权重)'},
        ),
    ]
