# Generated by Django 5.0.3 on 2024-03-29 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='请求时间')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('total_energy_consumption', models.DecimalField(decimal_places=2, default=1.0, help_text='万吨标准煤', max_digits=10, verbose_name='能源消费总量')),
                ('coal', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='煤炭占比')),
                ('petroleum', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='石油占比')),
                ('natural_gas', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='天然气占比')),
                ('power_and_other', models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='一次电力及其他能源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源消耗水平',
            },
        ),
        migrations.CreateModel(
            name='EnergyImportAndExportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('petroleum_i', models.DecimalField(decimal_places=2, default=1.0, help_text='进口（万吨）', max_digits=10, verbose_name='石油')),
                ('coal_i', models.DecimalField(decimal_places=2, default=1.0, help_text='进口（万吨）', max_digits=10, verbose_name='煤炭')),
                ('power_i', models.DecimalField(decimal_places=2, default=1.0, help_text='进口（亿千瓦时）', max_digits=10, verbose_name='电力')),
                ('petroleum_e', models.DecimalField(decimal_places=2, default=1.0, help_text='出口（万吨）', max_digits=10, verbose_name='石油')),
                ('coal_e', models.DecimalField(decimal_places=2, default=1.0, help_text='出口（万吨）', max_digits=10, verbose_name='煤炭')),
                ('power_e', models.DecimalField(decimal_places=2, default=1.0, help_text='出口（亿千瓦时）', max_digits=10, verbose_name='电力')),
                ('all_i', models.DecimalField(decimal_places=2, default=1.0, help_text='进口（万吨标准煤）', max_digits=10, verbose_name='可供消费的能源总量')),
                ('all_e', models.DecimalField(decimal_places=2, default=1.0, help_text='出口（万吨标准煤）', max_digits=10, verbose_name='可供消费的能源总量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源进出口量',
            },
        ),
        migrations.CreateModel(
            name='EnergyProductionAndInventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('total_energy_available_for_consumption', models.DecimalField(decimal_places=2, default=1.0, help_text='万吨标准煤', max_digits=10, verbose_name='可供消费的能源总量')),
                ('total_production_of_primary_energy', models.DecimalField(decimal_places=2, default=1.0, help_text='万吨标准煤', max_digits=10, verbose_name='一次能源生产总量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '能源平衡总和',
            },
        ),
        migrations.CreateModel(
            name='NewEnergyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('energy_type', models.CharField(choices=[('太阳能源', '太阳能源'), ('风力能源', '风力能源'), ('水利能源', '水利能源'), ('生物质能', '生物质能'), ('其他能源', '其他能源')], default='其他能源', max_length=50, verbose_name='能源类型')),
                ('value', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='产量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '新能源结构及趋势',
            },
        ),
        migrations.CreateModel(
            name='PowerGenerationInstalledCapacityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('thermal_power', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='火电')),
                ('hydropower', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='水电')),
                ('nuclear_power', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='核电')),
                ('wind_power', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='风电')),
                ('solar_power_generation', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='太阳能发电')),
                ('other_power', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='其他')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '发电装机容量',
            },
        ),
        migrations.CreateModel(
            name='MineralDevelopmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], max_length=100, verbose_name='行政单位')),
                ('year', models.IntegerField(default=2000, unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('coal', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='煤炭')),
                ('petroleum', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='石油')),
                ('gas', models.DecimalField(decimal_places=2, default=1.0, help_text='亿立方米', max_digits=10, verbose_name='天然气')),
                ('coalbed_methane', models.DecimalField(decimal_places=2, default=1.0, help_text='亿立方米', max_digits=10, verbose_name='煤层气')),
                ('shale_gas', models.DecimalField(decimal_places=2, default=1.0, help_text='亿立方米', max_digits=10, verbose_name='页岩气')),
                ('iron', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='铁矿')),
                ('manganese', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='锰矿')),
                ('ferrochrome', models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='铬铁矿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '矿产开发产量',
                'unique_together': {('year', 'region')},
            },
        ),
        migrations.CreateModel(
            name='RegionalResourceFacilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], max_length=100, verbose_name='行政单位')),
                ('name', models.CharField(max_length=30, verbose_name='设施')),
                ('do', models.CharField(max_length=30, verbose_name='工作')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='数目')),
                ('up', models.CharField(choices=[('吨', '吨'), ('万吨', '万吨'), ('公顷', '公顷'), ('万公顷', '万公顷'), ('亩', '亩'), ('万亩', '万亩'), ('千瓦时', '千瓦时'), ('亿千瓦时', '亿千瓦时')], default='吨', max_length=10, verbose_name='单位')),
                ('when', models.DateField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区资源设施使用情况',
                'unique_together': {('region', 'name')},
            },
        ),
    ]
