# Generated by Django 5.0.3 on 2024-03-29 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInvestmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('energy_investment', models.DecimalField(decimal_places=2, default=1.0, help_text='亿元', max_digits=10, verbose_name='能源重点项目投资')),
                ('new_energy_storage_projects_power', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦(功率)', max_digits=10, verbose_name='投运新型储能项目累计装机规模')),
                ('new_energy_storage_projects', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦时(电量)', max_digits=10, verbose_name='投运新型储能项目累计装机规模')),
                ('electricity_trading', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='电力市场交易电量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '全国市场交易及投资建设',
            },
        ),
    ]
