# Generated by Django 5.0.3 on 2024-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0003_energydevelopanddemandmodel_energyreservemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='central_South_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='中南'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='central_South_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='中南'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='east_China_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='华东'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='east_China_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='华东'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='north_China_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='华北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='north_China_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='华北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='northeast_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='东北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='northeast_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='东北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='northwest_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='西北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='northwest_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='西北'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='southwest_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='西南'),
        ),
        migrations.AddField(
            model_name='energydevelopanddemandmodel',
            name='southwest_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='西南'),
        ),
    ]
