# Generated by Django 5.0.3 on 2024-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0004_energydevelopanddemandmodel_central_south_dm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinvestmentmodel',
            name='coal_methane',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='亿立方米', max_digits=10, verbose_name='煤层气产量'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='central_South_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='中南'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='central_South_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='中南'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='east_China_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='华东'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='east_China_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='华东'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='north_China_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='华北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='north_China_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='华北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='northeast_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='东北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='northeast_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='东北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='northwest_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='西北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='northwest_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='西北'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='southwest_dm',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(需求)', max_digits=10, verbose_name='西南'),
        ),
        migrations.AlterField(
            model_name='energydevelopanddemandmodel',
            name='southwest_dv',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦(开发)', max_digits=10, verbose_name='西南'),
        ),
    ]
