# Generated by Django 5.0.3 on 2024-03-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0005_marketinvestmentmodel_coal_methane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyreservemodel',
            name='coal',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='煤炭'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='geothermal',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='地热'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='natural_gas',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='天然气'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='petroleum',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='石油'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='range',
            field=models.CharField(choices=[('全国', '全国'), ('全球', '全球')], default='全球', max_length=10, verbose_name='统计范围'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='sun',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='太阳能'),
        ),
        migrations.AddField(
            model_name='energyreservemodel',
            name='wind',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='%', max_digits=3, verbose_name='风能'),
        ),
    ]
