# Generated by Django 5.0.3 on 2024-03-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0006_energyreservemodel_coal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyreservemodel',
            name='geothermal',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='兆瓦', max_digits=10, verbose_name='地热'),
        ),
    ]
