# Generated by Django 5.0.3 on 2024-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0007_alter_energyreservemodel_geothermal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyreservemodel',
            name='coal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='煤炭'),
        ),
        migrations.AlterField(
            model_name='energyreservemodel',
            name='geothermal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='地热'),
        ),
        migrations.AlterField(
            model_name='energyreservemodel',
            name='natural_gas',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='天然气'),
        ),
        migrations.AlterField(
            model_name='energyreservemodel',
            name='petroleum',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='石油'),
        ),
        migrations.AlterField(
            model_name='energyreservemodel',
            name='sun',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='太阳能'),
        ),
        migrations.AlterField(
            model_name='energyreservemodel',
            name='wind',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='风能'),
        ),
    ]
