# Generated by Django 5.0.3 on 2024-03-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0010_alter_energyreservemodel_coal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyreservemodel',
            name='petroleum',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='亿吨', max_digits=10, verbose_name='石油'),
        ),
    ]
