# Generated by Django 5.0.3 on 2024-03-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0013_alter_energyreservemodel_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyreservemodel',
            name='sun',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦', max_digits=10, verbose_name='太阳能'),
        ),
    ]
