# Generated by Django 5.0.3 on 2024-03-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0014_alter_energyreservemodel_sun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinvestmentmodel',
            name='electricity_trading',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='百亿千瓦时', max_digits=10, verbose_name='电力市场交易电量'),
        ),
    ]
