# Generated by Django 5.0.3 on 2024-03-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuYuanApplication', '0015_alter_marketinvestmentmodel_electricity_trading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionalResourceFacilitiesModel',
        ),
    ]
