# Generated by Django 5.0.3 on 2024-04-23 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=10, verbose_name='省份')),
                ('wind_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='风能')),
                ('water_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='水利')),
                ('light_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='光伏')),
                ('biomass_energy_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='生物质能')),
                ('geothermal_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='地热')),
                ('sea_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='海洋')),
                ('wind_res', models.DecimalField(decimal_places=2, default=1.0, help_text='兆瓦时（储量）', max_digits=10, verbose_name='风能')),
                ('water_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（储量）', max_digits=10, verbose_name='水利')),
                ('light_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（储量）', max_digits=10, verbose_name='光伏')),
                ('biomass_energy_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（储量）', max_digits=10, verbose_name='生物质能')),
                ('geothermal_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（储量）', max_digits=10, verbose_name='地热')),
                ('sea_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（储量）', max_digits=10, verbose_name='海洋')),
                ('hydrogen', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦时（产量）', max_digits=10, verbose_name='氢能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区再生能源储量/产量统计',
            },
        ),
        migrations.CreateModel(
            name='RenewableEnergyInstallationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=10, verbose_name='省份')),
                ('water', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='水电装机')),
                ('wind', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='风电装机')),
                ('sun', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='光伏发电')),
                ('biomass', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦', max_digits=10, verbose_name='生物质发电')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区可再生能源装机',
            },
        ),
        migrations.CreateModel(
            name='MainEnergyProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], max_length=100, verbose_name='行政单位')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('raw_coal', models.DecimalField(decimal_places=1, default=1.0, help_text='万吨', max_digits=10, verbose_name='原煤')),
                ('crude_oil', models.DecimalField(decimal_places=1, default=1.0, help_text='万吨', max_digits=10, verbose_name='原油')),
                ('fire_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='火力发电量')),
                ('water_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='水力发电量')),
                ('wind_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='风力发电量')),
                ('sun_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='太阳能发电量')),
                ('nuclear_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='核能发电量')),
                ('all_power', models.DecimalField(decimal_places=1, default=1.0, help_text='亿千瓦时', max_digits=10, verbose_name='总发电量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '规模以上企业主要能源产量',
                'unique_together': {('year', 'province')},
            },
        ),
        migrations.CreateModel(
            name='RegionalResourceFacilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], max_length=100, verbose_name='行政单位')),
                ('type', models.CharField(choices=[('再生能源', '再生能源'), ('有限能源', '有限能源')], default='再生能源', max_length=20, verbose_name='能源归类')),
                ('name', models.CharField(max_length=30, verbose_name='设施')),
                ('do', models.CharField(max_length=30, verbose_name='工作')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='数目')),
                ('up', models.CharField(choices=[('吨', '吨'), ('万吨', '万吨'), ('公顷', '公顷'), ('万公顷', '万公顷'), ('亩', '亩'), ('万亩', '万亩'), ('千瓦时', '千瓦时'), ('万千瓦时', '万千瓦时'), ('亿千瓦时', '亿千瓦时')], default='吨', max_length=10, verbose_name='单位')),
                ('when', models.DateField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区资源设施使用情况',
                'unique_together': {('province', 'name')},
            },
        ),
    ]
