# Generated by Django 5.0.3 on 2024-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricfieldmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='运行状态'),
        ),
    ]
