# Generated by Django 5.0.3 on 2024-03-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0002_electricfieldmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricfieldfaultmodel',
            name='electric_field',
            field=models.ForeignKey(limit_choices_to={'state': False}, on_delete=django.db.models.deletion.CASCADE, to='renew.electricfieldmodel', unique=True, verbose_name='电场信息'),
        ),
        migrations.AlterField(
            model_name='electricfieldmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
