# Generated by Django 5.0.3 on 2024-03-30 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0003_alter_electricfieldfaultmodel_electric_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainenergyproductionmodel',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份'),
        ),
    ]
