# Generated by Django 5.0.3 on 2024-03-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0004_alter_mainenergyproductionmodel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalResourceFacilitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], max_length=100, verbose_name='行政单位')),
                ('name', models.CharField(max_length=30, verbose_name='设施')),
                ('do', models.CharField(max_length=30, verbose_name='工作')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='数目')),
                ('up', models.CharField(choices=[('吨', '吨'), ('万吨', '万吨'), ('公顷', '公顷'), ('万公顷', '万公顷'), ('亩', '亩'), ('万亩', '万亩'), ('千瓦时', '千瓦时'), ('亿千瓦时', '亿千瓦时')], default='吨', max_length=10, verbose_name='单位')),
                ('when', models.DateField(verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区资源设施使用情况',
                'unique_together': {('region', 'name')},
            },
        ),
    ]
