# Generated by Django 5.0.3 on 2024-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0005_regionalresourcefacilitiesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalresourcefacilitiesmodel',
            name='up',
            field=models.CharField(choices=[('吨', '吨'), ('万吨', '万吨'), ('公顷', '公顷'), ('万公顷', '万公顷'), ('亩', '亩'), ('万亩', '万亩'), ('千瓦时', '千瓦时'), ('万千瓦时', '万千瓦时'), ('亿千瓦时', '亿千瓦时')], default='吨', max_length=10, verbose_name='单位'),
        ),
    ]
