# Generated by Django 5.0.3 on 2024-03-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0006_alter_regionalresourcefacilitiesmodel_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricFieldFaultModel',
        ),
        migrations.DeleteModel(
            name='ElectricFieldModel',
        ),
    ]
