# Generated by Django 5.0.3 on 2024-03-30 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renew', '0007_delete_electricfieldfaultmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2099)], verbose_name='年份')),
                ('province', models.CharField(choices=[('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆')], default='安徽', max_length=10, verbose_name='省份')),
                ('wind_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（产量）', max_digits=10, verbose_name='风能')),
                ('water_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（产量）', max_digits=10, verbose_name='水利')),
                ('light_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（产量）', max_digits=10, verbose_name='光伏')),
                ('biomass_energy_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（产量）', max_digits=10, verbose_name='生物质能')),
                ('geothermal_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（产量）', max_digits=10, verbose_name='地热')),
                ('sea_pro', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（产量）', max_digits=10, verbose_name='海洋')),
                ('wind_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（储量）', max_digits=10, verbose_name='风能')),
                ('water_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（储量）', max_digits=10, verbose_name='水利')),
                ('light_res', models.DecimalField(decimal_places=2, default=1.0, help_text='亿千瓦（储量）', max_digits=10, verbose_name='光伏')),
                ('biomass_energy_res', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（储量）', max_digits=10, verbose_name='生物质能')),
                ('geothermal_res', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（储量）', max_digits=10, verbose_name='地热')),
                ('sea_res', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（储量）', max_digits=10, verbose_name='海洋')),
                ('hydrogen', models.DecimalField(decimal_places=2, default=1.0, help_text='万千瓦（产量）', max_digits=10, verbose_name='氢能')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地区能源储量/产量统计',
            },
        ),
    ]
